// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIi7uvCdkeIJuNd7dX2cg-Vk461ry-VJk',
    appId: '1:376827351742:web:43ed7f951ce5664e7a44ef',
    messagingSenderId: '376827351742',
    projectId: 'muffin-my-app',
    authDomain: 'muffin-my-app.firebaseapp.com',
    storageBucket: 'muffin-my-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXUfMSkTbO3ni73TRzpY3EWz3K1EHJCxY',
    appId: '1:376827351742:android:a9498f21d5beb9137a44ef',
    messagingSenderId: '376827351742',
    projectId: 'muffin-my-app',
    storageBucket: 'muffin-my-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAng2L3gjPi7uw3IKIpDp3rnHa965VOVTE',
    appId: '1:376827351742:ios:29b851c16e96a53d7a44ef',
    messagingSenderId: '376827351742',
    projectId: 'muffin-my-app',
    storageBucket: 'muffin-my-app.appspot.com',
    iosClientId: '376827351742-ic9eesflqh27vod3rl0dkic5cknu8ce3.apps.googleusercontent.com',
    iosBundleId: 'com.example.muffin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAng2L3gjPi7uw3IKIpDp3rnHa965VOVTE',
    appId: '1:376827351742:ios:29b851c16e96a53d7a44ef',
    messagingSenderId: '376827351742',
    projectId: 'muffin-my-app',
    storageBucket: 'muffin-my-app.appspot.com',
    iosClientId: '376827351742-ic9eesflqh27vod3rl0dkic5cknu8ce3.apps.googleusercontent.com',
    iosBundleId: 'com.example.muffin',
  );
}
